layout_spectrum: 0.2437276
color:
  saturation: 0.3924731
  brandStrength: 0.08821708
  lightness: 0.4731183
  rhythmicContrast: 0.5519713
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.3870968
name: Krocker Photography
